//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  /** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  content: Content;
  contentConnection: ContentConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContentArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContentConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContentFilter>;
};

export type DocumentFilter = {
  content?: InputMaybe<ContentFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Content | Folder;

export type ContentSiteReel = {
  __typename?: 'ContentSiteReel';
  label?: Maybe<Scalars['String']['output']>;
  duration?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
};

export type ContentSiteHud = {
  __typename?: 'ContentSiteHud';
  fps?: Maybe<Scalars['String']['output']>;
  shutter?: Maybe<Scalars['String']['output']>;
  iris?: Maybe<Scalars['String']['output']>;
  ei?: Maybe<Scalars['String']['output']>;
  nd?: Maybe<Scalars['String']['output']>;
  cam?: Maybe<Scalars['String']['output']>;
  fcl?: Maybe<Scalars['String']['output']>;
  media?: Maybe<Scalars['String']['output']>;
  tc_start?: Maybe<Scalars['String']['output']>;
};

export type ContentSite = {
  __typename?: 'ContentSite';
  brand?: Maybe<Scalars['String']['output']>;
  role?: Maybe<Scalars['String']['output']>;
  hero_line1?: Maybe<Scalars['String']['output']>;
  hero_line2?: Maybe<Scalars['String']['output']>;
  tagline?: Maybe<Scalars['String']['output']>;
  reel?: Maybe<ContentSiteReel>;
  email?: Maybe<Scalars['String']['output']>;
  contact_line?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  hud?: Maybe<ContentSiteHud>;
};

export type ContentAbout = {
  __typename?: 'ContentAbout';
  label?: Maybe<Scalars['String']['output']>;
  loc?: Maybe<Scalars['String']['output']>;
  pull?: Maybe<Scalars['String']['output']>;
  paragraphs?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  collaborators?: Maybe<Scalars['String']['output']>;
};

export type ContentCategoriesProjects = {
  __typename?: 'ContentCategoriesProjects';
  title?: Maybe<Scalars['String']['output']>;
  year?: Maybe<Scalars['String']['output']>;
  meta?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
  placeholder?: Maybe<Scalars['Boolean']['output']>;
};

export type ContentCategories = {
  __typename?: 'ContentCategories';
  title?: Maybe<Scalars['String']['output']>;
  count?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
  id?: Maybe<Scalars['String']['output']>;
  projects?: Maybe<Array<Maybe<ContentCategoriesProjects>>>;
};

export type Content = Node & Document & {
  __typename?: 'Content';
  site?: Maybe<ContentSite>;
  about?: Maybe<ContentAbout>;
  categories?: Maybe<Array<Maybe<ContentCategories>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ContentSiteReelFilter = {
  label?: InputMaybe<StringFilter>;
  duration?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type ContentSiteHudFilter = {
  fps?: InputMaybe<StringFilter>;
  shutter?: InputMaybe<StringFilter>;
  iris?: InputMaybe<StringFilter>;
  ei?: InputMaybe<StringFilter>;
  nd?: InputMaybe<StringFilter>;
  cam?: InputMaybe<StringFilter>;
  fcl?: InputMaybe<StringFilter>;
  media?: InputMaybe<StringFilter>;
  tc_start?: InputMaybe<StringFilter>;
};

export type ContentSiteFilter = {
  brand?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  hero_line1?: InputMaybe<StringFilter>;
  hero_line2?: InputMaybe<StringFilter>;
  tagline?: InputMaybe<StringFilter>;
  reel?: InputMaybe<ContentSiteReelFilter>;
  email?: InputMaybe<StringFilter>;
  contact_line?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  hud?: InputMaybe<ContentSiteHudFilter>;
};

export type ContentAboutFilter = {
  label?: InputMaybe<StringFilter>;
  loc?: InputMaybe<StringFilter>;
  pull?: InputMaybe<StringFilter>;
  paragraphs?: InputMaybe<StringFilter>;
  collaborators?: InputMaybe<StringFilter>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ContentCategoriesProjectsFilter = {
  title?: InputMaybe<StringFilter>;
  year?: InputMaybe<StringFilter>;
  meta?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
  placeholder?: InputMaybe<BooleanFilter>;
};

export type ContentCategoriesFilter = {
  title?: InputMaybe<StringFilter>;
  count?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
  id?: InputMaybe<StringFilter>;
  projects?: InputMaybe<ContentCategoriesProjectsFilter>;
};

export type ContentFilter = {
  site?: InputMaybe<ContentSiteFilter>;
  about?: InputMaybe<ContentAboutFilter>;
  categories?: InputMaybe<ContentCategoriesFilter>;
};

export type ContentConnectionEdges = {
  __typename?: 'ContentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Content>;
};

export type ContentConnection = Connection & {
  __typename?: 'ContentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ContentConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateContent: Content;
  createContent: Content;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateContentArgs = {
  relativePath: Scalars['String']['input'];
  params: ContentMutation;
};


export type MutationCreateContentArgs = {
  relativePath: Scalars['String']['input'];
  params: ContentMutation;
};

export type DocumentUpdateMutation = {
  content?: InputMaybe<ContentMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  content?: InputMaybe<ContentMutation>;
};

export type ContentSiteReelMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  duration?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type ContentSiteHudMutation = {
  fps?: InputMaybe<Scalars['String']['input']>;
  shutter?: InputMaybe<Scalars['String']['input']>;
  iris?: InputMaybe<Scalars['String']['input']>;
  ei?: InputMaybe<Scalars['String']['input']>;
  nd?: InputMaybe<Scalars['String']['input']>;
  cam?: InputMaybe<Scalars['String']['input']>;
  fcl?: InputMaybe<Scalars['String']['input']>;
  media?: InputMaybe<Scalars['String']['input']>;
  tc_start?: InputMaybe<Scalars['String']['input']>;
};

export type ContentSiteMutation = {
  brand?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  hero_line1?: InputMaybe<Scalars['String']['input']>;
  hero_line2?: InputMaybe<Scalars['String']['input']>;
  tagline?: InputMaybe<Scalars['String']['input']>;
  reel?: InputMaybe<ContentSiteReelMutation>;
  email?: InputMaybe<Scalars['String']['input']>;
  contact_line?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  hud?: InputMaybe<ContentSiteHudMutation>;
};

export type ContentAboutMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  loc?: InputMaybe<Scalars['String']['input']>;
  pull?: InputMaybe<Scalars['String']['input']>;
  paragraphs?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  collaborators?: InputMaybe<Scalars['String']['input']>;
};

export type ContentCategoriesProjectsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  year?: InputMaybe<Scalars['String']['input']>;
  meta?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
  placeholder?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ContentCategoriesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  count?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
  id?: InputMaybe<Scalars['String']['input']>;
  projects?: InputMaybe<Array<InputMaybe<ContentCategoriesProjectsMutation>>>;
};

export type ContentMutation = {
  site?: InputMaybe<ContentSiteMutation>;
  about?: InputMaybe<ContentAboutMutation>;
  categories?: InputMaybe<Array<InputMaybe<ContentCategoriesMutation>>>;
};

export type StringFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type ContentSiteReelFilter = {
  label?: StringFilter | null | undefined;
  duration?: StringFilter | null | undefined;
  href?: StringFilter | null | undefined;
};

export type ContentSiteHudFilter = {
  fps?: StringFilter | null | undefined;
  shutter?: StringFilter | null | undefined;
  iris?: StringFilter | null | undefined;
  ei?: StringFilter | null | undefined;
  nd?: StringFilter | null | undefined;
  cam?: StringFilter | null | undefined;
  fcl?: StringFilter | null | undefined;
  media?: StringFilter | null | undefined;
  tc_start?: StringFilter | null | undefined;
};

export type ContentSiteFilter = {
  brand?: StringFilter | null | undefined;
  role?: StringFilter | null | undefined;
  hero_line1?: StringFilter | null | undefined;
  hero_line2?: StringFilter | null | undefined;
  tagline?: StringFilter | null | undefined;
  reel?: ContentSiteReelFilter | null | undefined;
  email?: StringFilter | null | undefined;
  contact_line?: StringFilter | null | undefined;
  location?: StringFilter | null | undefined;
  hud?: ContentSiteHudFilter | null | undefined;
};

export type ContentAboutFilter = {
  label?: StringFilter | null | undefined;
  loc?: StringFilter | null | undefined;
  pull?: StringFilter | null | undefined;
  paragraphs?: StringFilter | null | undefined;
  collaborators?: StringFilter | null | undefined;
};

export type BooleanFilter = {
  eq?: boolean | null | undefined;
  exists?: boolean | null | undefined;
};

export type ContentCategoriesProjectsFilter = {
  title?: StringFilter | null | undefined;
  year?: StringFilter | null | undefined;
  meta?: StringFilter | null | undefined;
  href?: StringFilter | null | undefined;
  placeholder?: BooleanFilter | null | undefined;
};

export type ContentCategoriesFilter = {
  title?: StringFilter | null | undefined;
  count?: StringFilter | null | undefined;
  desc?: StringFilter | null | undefined;
  id?: StringFilter | null | undefined;
  projects?: ContentCategoriesProjectsFilter | null | undefined;
};

export type ContentFilter = {
  site?: ContentSiteFilter | null | undefined;
  about?: ContentAboutFilter | null | undefined;
  categories?: ContentCategoriesFilter | null | undefined;
};

export type ContentPartsFragment = { __typename: 'Content', site: { __typename: 'ContentSite', brand: string | null, role: string | null, hero_line1: string | null, hero_line2: string | null, tagline: string | null, email: string | null, contact_line: string | null, location: string | null, reel: { __typename: 'ContentSiteReel', label: string | null, duration: string | null, href: string | null } | null, hud: { __typename: 'ContentSiteHud', fps: string | null, shutter: string | null, iris: string | null, ei: string | null, nd: string | null, cam: string | null, fcl: string | null, media: string | null, tc_start: string | null } | null } | null, about: { __typename: 'ContentAbout', label: string | null, loc: string | null, pull: string | null, paragraphs: Array<string | null> | null, collaborators: string | null } | null, categories: Array<{ __typename: 'ContentCategories', title: string | null, count: string | null, desc: string | null, id: string | null, projects: Array<{ __typename: 'ContentCategoriesProjects', title: string | null, year: string | null, meta: string | null, href: string | null, placeholder: boolean | null } | null> | null } | null> | null };

export type ContentQueryVariables = Exact<{
  relativePath: string;
}>;


export type ContentQuery = { content: { __typename: 'Content', id: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, site: { __typename: 'ContentSite', brand: string | null, role: string | null, hero_line1: string | null, hero_line2: string | null, tagline: string | null, email: string | null, contact_line: string | null, location: string | null, reel: { __typename: 'ContentSiteReel', label: string | null, duration: string | null, href: string | null } | null, hud: { __typename: 'ContentSiteHud', fps: string | null, shutter: string | null, iris: string | null, ei: string | null, nd: string | null, cam: string | null, fcl: string | null, media: string | null, tc_start: string | null } | null } | null, about: { __typename: 'ContentAbout', label: string | null, loc: string | null, pull: string | null, paragraphs: Array<string | null> | null, collaborators: string | null } | null, categories: Array<{ __typename: 'ContentCategories', title: string | null, count: string | null, desc: string | null, id: string | null, projects: Array<{ __typename: 'ContentCategoriesProjects', title: string | null, year: string | null, meta: string | null, href: string | null, placeholder: boolean | null } | null> | null } | null> | null } };

export type ContentConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: ContentFilter | null | undefined;
}>;


export type ContentConnectionQuery = { contentConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Content', id: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, site: { __typename: 'ContentSite', brand: string | null, role: string | null, hero_line1: string | null, hero_line2: string | null, tagline: string | null, email: string | null, contact_line: string | null, location: string | null, reel: { __typename: 'ContentSiteReel', label: string | null, duration: string | null, href: string | null } | null, hud: { __typename: 'ContentSiteHud', fps: string | null, shutter: string | null, iris: string | null, ei: string | null, nd: string | null, cam: string | null, fcl: string | null, media: string | null, tc_start: string | null } | null } | null, about: { __typename: 'ContentAbout', label: string | null, loc: string | null, pull: string | null, paragraphs: Array<string | null> | null, collaborators: string | null } | null, categories: Array<{ __typename: 'ContentCategories', title: string | null, count: string | null, desc: string | null, id: string | null, projects: Array<{ __typename: 'ContentCategoriesProjects', title: string | null, year: string | null, meta: string | null, href: string | null, placeholder: boolean | null } | null> | null } | null> | null } | null } | null> | null } };

export const ContentPartsFragmentDoc = gql`
    fragment ContentParts on Content {
  __typename
  site {
    __typename
    brand
    role
    hero_line1
    hero_line2
    tagline
    reel {
      __typename
      label
      duration
      href
    }
    email
    contact_line
    location
    hud {
      __typename
      fps
      shutter
      iris
      ei
      nd
      cam
      fcl
      media
      tc_start
    }
  }
  about {
    __typename
    label
    loc
    pull
    paragraphs
    collaborators
  }
  categories {
    __typename
    title
    count
    desc
    id
    projects {
      __typename
      title
      year
      meta
      href
      placeholder
    }
  }
}
    `;
export const ContentDocument = gql`
    query content($relativePath: String!) {
  content(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ContentParts
  }
}
    ${ContentPartsFragmentDoc}`;
export const ContentConnectionDocument = gql`
    query contentConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ContentFilter) {
  contentConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ContentParts
      }
    }
  }
}
    ${ContentPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      content(variables: ContentQueryVariables, options?: C): Promise<{data: ContentQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContentQueryVariables, query: string}> {
        return requester<{data: ContentQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContentQueryVariables, query: string}, ContentQueryVariables>(ContentDocument, variables, options);
      },
    contentConnection(variables?: ContentConnectionQueryVariables, options?: C): Promise<{data: ContentConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContentConnectionQueryVariables, query: string}> {
        return requester<{data: ContentConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContentConnectionQueryVariables, query: string}, ContentConnectionQueryVariables>(ContentConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

export type { Exact };

  